### ISSUE TITLE
Missing Letter

### ISSUE THREAD

**Issue by imhalid** [imhalid/cv-builder#1]
The value entered in the inputs enters the local storage with the last letter missing.

**Comment by baspinarenes** [comment]
Since setState is an async operation, state value is changing after localstorage was setted. Solution:

```
const updateCv = (key, value) => {
    const newCv = { ...cv, [key]: value };
    setCv(newCv);
    localStorage.setItem("cv", JSON.stringify(newCv));
};
```

**Comment by imhalid** [comment]
Thank you very much, it works great 🎉🎉🎉
