### ISSUE TITLE
Socail Item Checkbox

### ISSUE THREAD

**Issue by fuykun** [imhalid/cv-builder#2]
social item checkbox continues to display when disabled

**Comment by fuykun** [comment]
I solved that problem. Can I create pull request for this?

**Comment by imhalid** [comment]
yes, I am aware of this problem, I do not know exactly how to do it now, but I will fix it.

**Comment by fuykun** [comment]
i solved for you :) check pr

**Comment by imhalid** [comment]
Thank you :)
