### ISSUE TITLE
Overflow problem!

### ISSUE THREAD

**Issue by alikarakoc** [imhalid/cv-builder#8]
![image](https://user-images.githubusercontent.com/16520480/191242137-82d650c7-da44-4933-854b-2620ea7acae8.png)

I wanted to give it a try. But I noticed that there was no slipping down. Should it be like this?

Or is there really something wrong? :)

**Comment by imhalid** [comment]
Yes this is an error.🥲 

This project is a small project for those with a lot of experience right now. 😅

Normally a 2nd page is required, but I haven't been able to add such a feature yet. only single page is supported.

I'm sorry you encountered this problem. 😔

**Comment by alikarakoc** [comment]
I hope you improve it. It's very nice.
